      SUBROUTINE PLOT
      DIMENSION AB(100),FLINE(60)
      CHARACTER*1 IBLANK, IA, IB, IC, ID, IE, IZERO, LINE(60)
      DATA IA,IB,IC,ID,IE,IZERO/"G","#","M","*","+","0"/
      COMMON/INV/DIST(75),NSTAT,GRAV(75),GTOT(75),MAG(75),MTOT(75),NPOLY
     1,NSIDES(12),Z(12,25),X(12,25),ELEV(75),SL(12),DENSTY(12),CT,SUSCP(
     212),NBASE,IAN
      REAL MAG,NTOT 
      IBLANK = " "
      FMING=GRAV(1)
      FMINM=MAG(1)
      FMAXG=GRAV(1)
      FMAXM=MAG(1)
2000  FORMAT(' FMING,FMINM,FMAXG,FMAXM ',4F10.3)
      DO 15 I=1,NSTAT
      IF(GRAV(I).GT.FMAXG)FMAXG=GRAV(I)
      IF(GRAV(I).LT.FMING)FMING=GRAV(I)
      IF(GTOT(I).GT.FMAXG)FMAXG=GTOT(I)
      IF(GTOT(I).LT.FMING)FMING=GTOT(I)
      IF(MAG(I).GT.FMAXM)FMAXM=MAG(I)
      IF(MAG(I).LT.FMINM)FMINM=MAG(I)
      IF(MTOT(I).GT.FMAXM)FMAXM=MTOT(I)
      IF(MTOT(I).LT.FMINM)FMINM=MTOT(I)
  15  CONTINUE
      DIFG=ABS(FMAXG-FMING)
      DIFM=ABS(FMAXM-FMINM)
      DIFFG=DIFG/50.
      DIFFM=DIFM/50.
2001  FORMAT(' DIFG,DIFM,DIFFG,DIFFM ',4F10.3)
      WRITE(6,124)
      DO 16 I=1,6
  16  CONTINUE
      FLINE(I)=FMING+(DIFFG*10.*FLOAT(I-1))
      WRITE(6,125) (FLINE(J), J=1,6)
      WRITE(6,126)
      DO 17 I=1,6
  17  FLINE(I)=FMINM+(DIFFM*10.*FLOAT(I-1))
      WRITE(6,125)(FLINE(J),J=1,6)
      DTOT=DIST(NSTAT)-DIST(I)
      FINC=DTOT/FLOAT(NSTAT-1)
      NN=NSTAT+1
      DO 18 I=1,NN
  18  AB(I)=DIST(1)+(FINC*FLOAT(I-1))
      DO 19 I=1,NN
      IGRAV=(1-((FMAXG-GRAV(I))/DIFG))*50
2002  FORMAT(' DTOT,FINC,IGRAV,NSTAT ',2F10.3,2I10)
      IGTOT=(1-((FMAXG-GTOT(I))/DIFG))*50
      IMAG=(1-((FMAXM-MAG(I))/DIFM))*50
      IMTOT=(1-((FMAXM-MTOT(Ig))/DIFM))*50
      DO 20 J=1,50
  20  LINE(J)=IBLANK
      LINE(IGRAV)=IA
      LINE(IGTOT)=IB
      LINE(IMAG)=IC
      LINE(IMTOT)=ID
      IF(IGRAV.EQ.IGTOT)LINE(IGRAV)=IZERO
      IF(IMAG.EQ.IMTOT)LINE(IMAG)=IZERO
2003  FORMAT(' IGTOT,IMAG,IMTOT ',3I10)
      IF(IGRAV.EQ.IMAG.OR.IGTOT.EQ.IMAG)LINE(IMTOT)=IE
      IF(IGRAV.EQ.IMTOT.OR.IGTOT.EQ.IMTOT)LINE(IMTOT)=IE
  19  WRITE(6,127)AB(I),(LINE(J),J=1,50)
 124  FORMAT(' MGAL SCALE  G=OBSERVED,#=COMPUTED')
 125  FORMAT(1H,6F10.3)
 126  FORMAT(' GAMMA SCALE  X=OBSERVED,*=COMPUTED')
 127  FORMAT(' ', F6.2,1X,50A1)
      RETURN
      END
